steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/proxy_app:$_IMAGE_TAG',
           '--secret', 'id=PROXY_BASIC_AUTH_USER',
           '--secret', 'id=PROXY_BASIC_AUTH_PASSWORD', '.']
    secretEnv: ['PROXY_BASIC_AUTH_USER', 'PROXY_BASIC_AUTH_PASSWORD']
  - id: push
    name: gcr.io/cloud-builders/docker
    args: ['push', 'asia.gcr.io/$PROJECT_ID/proxy_app:$_IMAGE_TAG']
    waitFor:
      - build
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/PROXY_BASIC_AUTH_USER/versions/latest
      env: 'PROXY_BASIC_AUTH_USER'
    - versionName: projects/$PROJECT_ID/secrets/PROXY_BASIC_AUTH_PASSWORD/versions/latest
      env: 'PROXY_BASIC_AUTH_PASSWORD'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 900s
substitutions:
  _IMAGE_TAG: default_value